// <auto-generated />
using System;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.Koostisosa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Hind")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kirjeldus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Kogus")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Nimetus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PartiiId")
                        .HasColumnType("int");

                    b.Property<string>("Uhik")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PartiiId");

                    b.ToTable("Koostisosad");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Maitsmine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degusteerija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Hinne")
                        .HasColumnType("int");

                    b.Property<string>("Kommentaar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartiiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartiiId");

                    b.ToTable("Maitsmised");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Olu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Alkoholiprotsent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kirjeldus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tuup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Olud");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Partii", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kirjeldus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Kood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("OluId")
                        .HasColumnType("int");

                    b.Property<string>("Tulemus")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OluId");

                    b.ToTable("Partiid");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.PartiiFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FailiTee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PartiiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartiiId");

                    b.ToTable("PartiiFotod");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.PruulimisLogi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kasutaja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kirjeldus")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartiiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartiiId");

                    b.ToTable("PruulimisLogid");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Koostisosa", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Partii", "Partii")
                        .WithMany()
                        .HasForeignKey("PartiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partii");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Maitsmine", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Partii", "Partii")
                        .WithMany()
                        .HasForeignKey("PartiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partii");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Partii", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Olu", "Olu")
                        .WithMany()
                        .HasForeignKey("OluId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olu");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.PartiiFoto", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Partii", "Partii")
                        .WithMany()
                        .HasForeignKey("PartiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partii");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.PruulimisLogi", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Partii", "Partii")
                        .WithMany()
                        .HasForeignKey("PartiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partii");
                });
#pragma warning restore 612, 618
        }
    }
}
